INPUT_DIM_MODEL: 1
LEARNING_RATE: 0.001
FACTOR_LR: 0.5
PATIENCE_LR: 10
PATIENCE_ES: 50
LOG_WANDB: True
BATCH_SIZE: 16
EPOCHS: 300
NUM_WORKERS: 4
PREFETCH_FACTOR: 2
ACCELERATOR: gpu
DEVICES: [3]
SAVE_MODEL_TOP_K: 2
PRECISION: 16-mixed
USE_TRANSFER_LEARNING:
  CINE: False
  LGE: TRUE
